### ISSUE TITLE
Didn't get victory point

### ISSUE THREAD

**Issue by caseymh** [rysav/cs340spring2016#29]
I upgraded a settlement to a city which should have given me 10 victory points and let me win and I stayed at 9 points. The server also says I have 10 points.

**Comment by caseymh** [comment]
I couldn't trade but I could end my turn, The I then got to roll again, I rolled a 6 and then it crashed

**Comment by caseymh** [comment]
Got null pointer exception that caused the crash, That is why I changed it to P1, I don't know if it should be P1 or P2 but P1 says crash.

**Comment by caseymh** [comment]
Tried to win another way and Wasn't able to I had the same thing happen

**Comment by caseymh** [comment]
---

GameVersion: 40
Set model!
Current player: 0
LOCAL PLAYER: test, index: 0
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.points.PointsController.update(PointsController.java:64)
        at java.util.Observable.notifyObservers(Observable.java:159)
        at java.util.Observable.notifyObservers(Observable.java:115)
        at client.ClientManager.notifyObservers(ClientManager.java:108)
        at client.ClientManager.setModel(ClientManager.java:63)
        at client.communication.ServerPoller$1$1.run(ServerPoller.java:73)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
