### ISSUE TITLE
New Game Broke!

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#69]
Game froze upon entering a new game with two client players. (Note: broke only on one of the two clients, particularly the one that created the game)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.turntracker.TurnTrackerView.updatePlayer(TurnTrackerView.java:119)
        at client.turntracker.TurnTrackerController.updatePlayer(TurnTrackerController.java:70)
        at client.turntracker.TurnTrackerController.update(TurnTrackerController.java:140)
        at java.util.Observable.notifyObservers(Unknown Source)
        at java.util.Observable.notifyObservers(Unknown Source)
        at client.ClientManager.notifyObservers(ClientManager.java:108)
        at client.ClientManager.setModel(ClientManager.java:63)
        at client.communication.ServerPoller$1$1.run(ServerPoller.java:73)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by benjaminhafen** [comment]
I followed your steps and entered a new game with two client players, but I'm not able to reproduce this issue. Did you do anything other than create a new game and then join it with two clients to cause the crash?

**Comment by jangusbeef** [comment]
No. All I did was as stated. If it matters, the two clients were the first two players, and the second client to join added the AI players. 
Its happened twice to me now, but it is very intermittent and I can't pin down exactly how to re-produce it.
