### ISSUE TITLE
Crash on multiplayer place roads

### ISSUE THREAD

**Issue by cwpitts** [rysav/cs340spring2016#70]
Opened two clients, joined same game. Foobar placed correctly, but game crashed on barfoo.

Output and stack trace:

---

GameVersion: 0
Set model!
Current player: 1
LOCAL PLAYER: barfoo, index: 1
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at client.turntracker.TurnTrackerView.updatePlayer(TurnTrackerView.java:119)
    at client.turntracker.TurnTrackerController.updatePlayer(TurnTrackerController.java:73)
    at client.turntracker.TurnTrackerController.update(TurnTrackerController.java:140)
    at java.util.Observable.notifyObservers(Observable.java:159)
    at java.util.Observable.notifyObservers(Observable.java:115)
    at client.ClientManager.notifyObservers(ClientManager.java:108)
    at client.ClientManager.setModel(ClientManager.java:63)
    at client.communication.ServerPoller$1$1.run(ServerPoller.java:73)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by benjaminhafen** [comment]
I've been unable to replicate this issue. It may be an effect of #76. I'll close this issue, but if anyone is able to re-create it, let us know and we'll look into it again.
