### ISSUE TITLE
Robber Problem

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#74]
<s>When placing the robber on an empty tile, he defects to the desert upon ending the turn.</s> Afterwards, I am unable to move the robber when rolling a 7.

Edit: Robber likely moved by AI. However, this Issue still exists, likely by ending the turn before others have discarded?

**Comment by jangusbeef** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.map.RobView.setPlayers(RobView.java:110)
        at client.map.MapController.placeRobber(MapController.java:186)
        at client.map.MapView$1.placeRobber(MapView.java:162)
        at client.map.MapComponent$2.mouseClicked(MapComponent.java:574)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tlyon3** [comment]
Yeah so there is a problem with the fact that if an ai rolls a 7, and the next human player who's turn would come up has to discard, it won't work. This is because the ai's turn does not get paused until everyone has discarded. I've talked to the ta's about this and they are only going to test our client with all human players
