### ISSUE TITLE
Freezing/Extreme SlowDown

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#80]
While waiting for players, it becomes extremely difficult to add an AI player, often having to click the button constantly for a few seconds before it finally reacts. When the game was finally created, it threw the following exception:
LOCAL PLAYER: jangu, index: 0
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.turntracker.TurnTrackerController.updatePlayer(TurnTrackerController.java:73)
        at client.turntracker.TurnTrackerController.update(TurnTrackerController.java:140)
        at java.util.Observable.notifyObservers(Unknown Source)
        at java.util.Observable.notifyObservers(Unknown Source)
        at client.ClientManager.notifyObservers(ClientManager.java:108)
        at client.ClientManager.setModel(ClientManager.java:63)
        at client.communication.ServerPoller$1$1.run(ServerPoller.java:73)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by jangusbeef** [comment]
Might just be my slow af computer though...

**Comment by benjaminhafen** [comment]
I'm not able to replicate this issue, even on my relatively slow laptop. I'm going to go ahead and mark this as resolved because it might just be your computer being slow, but if others encounter the same issue, comment and we can re-open it.
